### ISSUE TITLE
Raw data signing is not supported for hardware wallets.

### ISSUE THREAD

**Issue by europound** [Zondax/ledger-polkadot#175]
polkadot Raw data signing is not supported for hardware wallets.

:link: [zboto Link](https://app.clickup.com/t/8677jw39g)

**Comment by europound** [comment]
Ledger Raw data signing is not supported for hardware wallets
https://polkadot.js.org/apps/#/signing

**Comment by europound** [comment]
why?

**Comment by ainhoa-a** [comment]
Hi @europound  we have already implemented this and it was sent to Ledger for review. It should be part of the next Polkadot release that will happen during late July.

**Comment by ghe0** [comment]
I am still getting the error when trying to login on subsquare.

**Comment by carlosala** [comment]
From our end, everything is done and released. Wallets should support it.
Please open an issue in your particular wallet!
